Урок 4.1 Прототипы. Задание 1
gpunker/thinknetika_js_course pull request #4
Opened 2022-07-03 06:35 UTC by gpunker

2022-07-03 19:04 UTC, fanisco requested changes

2022-07-03 19:04 UTC, fanisco commented on lesson4/part1/array_shuffle.js
> +}
Я бы предпочел делать сортировку на месте - модифицировать текущий массив

2022-07-03 19:04 UTC, fanisco commented on lesson4/part1/prototype_chain.js
> +    Human.call(this, { name: name, lastName: lastName, phoneNumber: phoneNumber })
Необходимо реализовать наследование через прототип

2022-07-03 19:04 UTC, fanisco commented on lesson4/part1/prototype_chain.js
> +    this.endDate = endDate
Необходим отдельный класс для бывших сотрудников

2022-07-05 09:19 UTC, gpunker commented on lesson4/part1/array_shuffle.js
> +}
т.е. это решение ошибочно? просто далеко не всегда можем хотеть модифицировать исходный массив

2022-07-08 07:22 UTC, fanisco requested changes

2022-07-08 07:22 UTC, fanisco commented on lesson4/part1/array_shuffle.js
> +    return
Небезопасный способ, потому что помимо нашей функции shuffle в прототипе и/или экземпляре массива могут быть иные свойства и методы. Тут придется переделать, можно использовать обычный sort, главное - делать изменения "на месте" - с текущим контекстом.

2022-07-08 07:22 UTC, fanisco commented on lesson4/part1/prototype_chain.js
> +    this.endDate = endDate
Не должно ли это быть свойством бывшего сотрудника?

2022-07-08 09:20 UTC, gpunker commented on lesson4/part1/prototype_chain.js
> +    this.endDate = endDate
Так оно как раз в функции-конструкторе ExEmployee

2022-07-08 10:18 UTC, gpunker commented on lesson4/part1/array_shuffle.js
> +    return
Поправлено

2022-07-08 10:18 UTC, merged